config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources 'users'

  resources 'profiles'
  post "/profiles/update_profile" => "profiles#update_profile"
  post "/profiles/update_profile_about_me" => "profiles#update_profile_about_me"

  resources 'friendships'#, :except => [ :create ]
  post "/friendships/update_friendship" => "friendships#update_friendship"

  resources 'languages'
  get "/languages/learns_languages" => "languages#learns_languages"

  post "/languages_users/remove_user_language" => "languages_users#remove_user_language"
  post "/languages_users/add_user_language" => "languages_users#add_user_language"
  post "/languages_users/remove_user_learns_language" => "languages_users#remove_user_learns_language"
  post "/languages_users/add_user_learns_language" => "languages_users#add_user_learns_language"

  post "/users_learn_languages/remove_user_learns_language" => "users_learn_languages#remove_user_learns_language"
  post "/users_learn_languages/add_user_learns_language" => "users_learn_languages#add_user_learns_language"

  resources 'visited_countries'
  post "visited_countries/add_country" => "visited_countries#add_country"
  post "visited_countries/remove_country" => "visited_countries#remove_country"

  resources 'posts'
  post "posts/create_post" => "posts#create_post"

  resources 'messages', only: [:show, :create]
  #get "/messages/show_conversation" => "messages#show_conversation"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
end

app/models/language.rb
class Language < ApplicationRecord
	has_many :languages_users
  	has_many :users, class_name: 'User', through: :languages_users, :source => :user
  	has_many :users_learn_languages
  	has_many :learn_users, class_name: 'User', through: :users_learn_languages, :source => :user
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
	def index
		@languages = Language.all
	end

	def show
		@learn_languages = Language.all
	end
end

app/views/languages/_languages_levels_partial.html.erb
<aside class="languages aside section">
    <div class="section-inner">
        <h2 class="heading">Languages
        <% if (logged_in? && current_user == @user) %>
        <button onclick="javascript:showLanguageLevelEdit();">
        <i class="fa fa-cog" aria-hidden="true"></i>
        </button>
        <% end %>
        </h2>
        <div class="content">
            <% if @user.languages.any? %>
                <ul class="list-unstyled">
                    <% @user.languages.each do |lang| %>
                        <li class="item">
                            <span class="title"><strong><%= lang.language %></strong></span>
                            <span class="level"><br class="visible-xs"/><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </span>
                        </li><!--//item-->
                    <% end %>    
                </ul>
            <% end %>
        </div><!--//content-->
    </div><!--//section-inner-->
</aside><!--//section-->     

app/views/languages/index.html.erb
<center><h1>Languages you already speak</h1></center>
<% @languages.each do |lang| %>
<ul>
	<% if user_knows_language?(lang.id) %>
	<li>
	<i class="fa fa-check" aria-hidden="true"></i>
        <%= h lang.language %>
 		<%= link_to 'remove', languages_users_remove_user_language_path(:remove_language_id => lang.id ), method: :post%>
    </li>
    <% else %>
    <li>
        <i class="fa fa-times" aria-hidden="true"></i>
        <%= h lang.language %>
        <%= link_to 'add', languages_users_add_user_language_path(:add_language_id => lang.id ), method: :post%>
    </li>
    <% end %>
</ul>
<% end %>
<center><%= link_to 'Back to your profile', user_path(current_user.id) %><br/></center>

app/views/languages/show.html.erb
<center><h1>Languages you are learning</h1></center>
<% @learn_languages.each do |lang| %>
<ul>
	<% if user_learns_language?(lang.id) %>
	<li>
	<i class="fa fa-check" aria-hidden="true"></i>
        <%= h lang.language %>
 		<%= link_to 'remove', users_learn_languages_remove_user_learns_language_path(:remove_language_id => lang.id ), method: :post%>
    </li>
    <% else %>
    <li>
        <i class="fa fa-times" aria-hidden="true"></i>
        <%= h lang.language %>
        <%= link_to 'add', users_learn_languages_add_user_learns_language_path(:add_language_id => lang.id ), method: :post%>
    </li>
    <% end %>
</ul>
<% end %>
<center><%= link_to 'Back to your profile', user_path(current_user.id) %><br/></center>