config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources 'users'

  resources 'profiles'
  post "/profiles/update_profile" => "profiles#update_profile"
  post "/profiles/update_profile_about_me" => "profiles#update_profile_about_me"

  resources 'friendships'#, :except => [ :create ]
  post "/friendships/update_friendship" => "friendships#update_friendship"

  resources 'languages'
  get "/languages/learns_languages" => "languages#learns_languages"

  post "/languages_users/remove_user_language" => "languages_users#remove_user_language"
  post "/languages_users/add_user_language" => "languages_users#add_user_language"
  post "/languages_users/remove_user_learns_language" => "languages_users#remove_user_learns_language"
  post "/languages_users/add_user_learns_language" => "languages_users#add_user_learns_language"

  post "/users_learn_languages/remove_user_learns_language" => "users_learn_languages#remove_user_learns_language"
  post "/users_learn_languages/add_user_learns_language" => "users_learn_languages#add_user_learns_language"

  resources 'visited_countries'
  post "visited_countries/add_country" => "visited_countries#add_country"
  post "visited_countries/remove_country" => "visited_countries#remove_country"

  resources 'posts'
  post "posts/create_post" => "posts#create_post"

  resources 'messages', only: [:show, :create]
  #get "/messages/show_conversation" => "messages#show_conversation"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
	has_one :profile, dependent: :destroy
	has_many :friendships
  	has_many :friends, :through => :friendships
  	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user
	has_many :languages_users
  	has_many :languages, class_name: 'Language', through: :languages_users, :source => :language
  	has_many :users_learn_languages
  	has_many :learn_languages, class_name: 'Language',  through: :users_learn_languages , :source => :language
  	has_many :visited_countries
  	has_many :posts
  	has_many :messages
  	has_many :sent_messages, :through => :messages
  	has_many :inverse_messages, :class_name => "Message", :foreign_key => "receiver_id"
	has_many :received_messages, :through => :inverse_messages, :source => :user
	has_secure_password
	before_save { self.email = email.downcase }
	validates :username, presence: true, uniqueness: { case_sensitive:false }, 
			  length: { minimum:3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
			  uniqueness: {case_sensitive: false}, 
			  format: { with: VALID_EMAIL_REGEX }
	validates :password_digest, length: { minimum:6 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all.where("id != ?", current_user.id)
	end

	def show
		@user = User.find(params[:id])
		@friends =  @user.inverse_friends + @user.friends 
		@visited_countries = @user.visited_countries.all	
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save && @user.build_profile.save
			flash[:notice] = "You have created an account"
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:username,:email,:password)
	end

end

app/views/users/index.html.erb
<center><h1>All registered users</h1></center>
<div class="container sections-wrapper">
    <div class="row">
    	<section class="latest section">
    		<div class="section-inner">
    			<div class="content" > 
				<% if @users.any? %>
					<% @users.each do |user|%>
					<ul>
						<li>
							username: <%= user.username %> ||
							id: <%= user.id %> ||
							<!--birth date: < % =#user. p rofile.birth_date %>-->
							<%= link_to 'Show profile', user_path(user.id) %> || 
							<% if friendship_request_sent?(user)  %>
								<% if  friendship_request_accepted?(user.id) %>
							 		<span>You are friends</span>
							 	<% elsif friendship_request_accepted?(user.id) == false %>
							 		<% if user.in?current_user.friends %>
							 			<span>Pending</span>
							 		<% elsif current_user.in?user.friends %>
							 			<%= link_to 'accept request', friendships_update_friendship_path(friend_id: user.id), method: :post %>
							 		<% end %>
							 	<% end %>
							<% else %>
							<%= link_to 'add friend', friendships_path(:user_id => current_user.id, :friend_id => user.id), method: :post %>
							<% end %> 
						</li>
					</ul>
					<% end %>
				<% end %>
				<%= link_to 'Back to your profile', user_path(current_user.id) %><br/>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<center>
<h1>Create an account</h1>

<% if @user.errors.any?  %>
<% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
<% end %>

<%= form_for @user do |f| %><br/>
  <%= f.label :Username %>
  <%= f.text_field :username %><br/>
  <%= f.label :email %>
  <%= f.email_field :email %><br/>
  <%= f.label :password %>
  <%= f.password_field :password%><br/>

  <%= f.submit %>
<% end %>
</center>

app/views/users/show.html.erb
<!-- ******HEADER****** --> 
<header class="header">
<div class="container">                       
	<% if @user.profile.avatar? %>
		<br/><%= image_tag @user.profile.avatar_url, class: 'profile-image img-responsive pull-left' %><br/>
	<% end %>
    <div class="profile-content pull-left">
        <h1 class="name"><%= @user.username %></h1>
        <div class="spoken_languages_div">
            <%= render :partial => 'languages_users/spoken_languages'%>
        </div>
        <div class="learning_languages_div">
            <%= render :partial => 'languages_users/learning_languages'%>
        </div>
    </div><!--//profile-->    
    <% if (logged_in? && current_user == @user) %>
		<%= link_to 'Edit profile', edit_profile_path(@user.profile.id), class: 'btn-cta-primary pull-right fa fa-cog' %><br/>
		<%= link_to 'Your friends', friendships_path, class: 'btn-cta-primary pull-right' %><br/>
		<%= link_to 'All users', users_path,  class: 'btn-cta-primary pull-right' %><br/>
	<% else %>
    <%= link_to 'Messsage', message_path(@user.id), class: 'btn-cta-primary pull-right fa fa-cog' %><br/>
		<%= link_to 'Back to your profile', user_path(current_user.id), class: 'btn-cta-primary pull-right' %><br/>
	<% end %>
    <!--<a class="btn btn-cta-primary pull-right" href="http://themes.3rdwavemedia.com/" target="_blank"><i class="fa fa-paper-plane"></i> Contact Me</a>  -->            
</div><!--//container-->
</header><!--//header-->

<div class="container sections-wrapper">
    <div class="row">
        <div class="primary col-md-8 col-sm-12 col-xs-12">
            <div class="user_profile_about_me_div">
                <%= render :partial => 'profiles/about_me_partial' %> 
            </div>
            <div class="user_posts_div">
                <%= render :partial => 'posts/posts_partial' %> 
            </div>
        </div><!--//primary-->
        <div class="secondary col-md-4 col-sm-12 col-xs-12">
            <div class="user_profile_info_div">
                <%= render :partial => 'profiles/user_profile_partial' %> 
            </div>
            <div class="visited_countries_div">
                <%= render :partial => 'visited_countries/visited_countries_partial' %>
            </div>
            <div class="languages_levels_div">
                <%= render :partial => 'languages/languages_levels_partial' %>
            </div>      
        </div><!--//secondary-->    
    </div><!--//row-->
</div><!--//masonry-->

<script type="text/javascript">
  function showVisitedCountryEdit() {

    div = document.getElementById('visited_countries_edit');
    var dates = document.querySelectorAll('*[id^="visited_country_remove"]');

    if(div.style.display == "none")
    {
        div.style.display = "block";
        for (i = 0; i < dates.length; i++)
        {
            dates[i].style.display = "inline-block";
        }
    }
    else
    {
        div.style.display = "none";
        for (i = 0; i < dates.length; i++)
        {
            dates[i].style.display = "none";
        }
    }
}
function showUserProfileEdit() {

    divedit = document.getElementById('user_profile_edit');
    divinfo = document.getElementById('user_profile_info');

    if(divinfo.style.display == "none")
    {
        divinfo.style.display = "block";
        divedit.style.display = "none"
    }
    else
    {
        divinfo.style.display = "none";
        divedit.style.display = "block"
    }
}
function showUserAboutMeEdit() {

    divedit = document.getElementById('user_about_me_edit');
    divinfo = document.getElementById('user_about_me');

    if(divinfo.style.display == "none")
    {
        divinfo.style.display = "block";
        divedit.style.display = "none"
    }
    else
    {
        divinfo.style.display = "none";
        divedit.style.display = "block"
    }
}
function showUserPostsEdit() {

    divedit = document.getElementById('user_post_edit');

    if(divedit.style.display == "none")
    {
        divedit.style.display = "block"
    }
    else
    {
        divedit.style.display = "none"
    }
}
function showLearnLanguagesEdit() {

    div = document.getElementById('learn_languages_edit');
    var dates = document.querySelectorAll('*[id^="learn_language_remove"]');

    if(div.style.display == "none")
    {
        div.style.display = "inline-block";
        for (i = 0; i < dates.length; i++)
        {
            dates[i].style.display = "inline-block";
        }
    }
    else
    {
        div.style.display = "none";
        for (i = 0; i < dates.length; i++)
        {
            dates[i].style.display = "none";
        }
    }
}
function showSpeakLanguagesEdit() {

    div = document.getElementById('spoken_languages_edit');
    var dates = document.querySelectorAll('*[id^="spoken_language_remove"]');

    if(div.style.display == "none")
    {
        div.style.display = "inline-block";
        for (i = 0; i < dates.length; i++)
        {
            dates[i].style.display = "inline-block";
        }
    }
    else
    {
        div.style.display = "none";
        for (i = 0; i < dates.length; i++)
        {
            dates[i].style.display = "none";
        }
    }
}
</script>