config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources 'users'

  resources 'profiles'
  post "/profiles/update_profile" => "profiles#update_profile"
  post "/profiles/update_profile_about_me" => "profiles#update_profile_about_me"

  resources 'friendships'#, :except => [ :create ]
  post "/friendships/update_friendship" => "friendships#update_friendship"

  resources 'languages'
  get "/languages/learns_languages" => "languages#learns_languages"

  post "/languages_users/remove_user_language" => "languages_users#remove_user_language"
  post "/languages_users/add_user_language" => "languages_users#add_user_language"
  post "/languages_users/remove_user_learns_language" => "languages_users#remove_user_learns_language"
  post "/languages_users/add_user_learns_language" => "languages_users#add_user_learns_language"

  post "/users_learn_languages/remove_user_learns_language" => "users_learn_languages#remove_user_learns_language"
  post "/users_learn_languages/add_user_learns_language" => "users_learn_languages#add_user_learns_language"

  resources 'visited_countries'
  post "visited_countries/add_country" => "visited_countries#add_country"
  post "visited_countries/remove_country" => "visited_countries#remove_country"

  resources 'posts'
  post "posts/create_post" => "posts#create_post"

  resources 'messages', only: [:show, :create]
  #get "/messages/show_conversation" => "messages#show_conversation"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
end

app/models/visited_country.rb
class VisitedCountry < ApplicationRecord
	
end

app/controllers/visited_countries_controller.rb
class VisitedCountriesController < ApplicationController

	def index
 		@countries = ISO3166::Country.all
	end

	def add_country
		#render plain: params[:visited_country][:country].inspect
		@country = params[:visited_country][:country]
		if VisitedCountry.where(user_id: current_user.id, country: @country).exists?
			#redirect_to user_path(current_user)
		else
			VisitedCountry.create(user_id: current_user.id, country: @country)
			#redirect_to user_path(current_user)
		end
		@visited_countries = current_user.visited_countries.all	
		@user = User.find(current_user.id)
		respond_to do |format|
    		format.js { render :action => "refresh_visited_countries_partial" }
 		end
	end
	def remove_country
		VisitedCountry.where(user_id: current_user.id, country: params[:visited_country]).delete_all
		#redirect_to user_path(current_user)
		@visited_countries = current_user.visited_countries.all	
		@user = User.find(current_user.id)
		respond_to do |format|
    		format.js { render :action => "refresh_visited_countries_partial" }
 		end
	end
	
	private
	def country_params
		params.require(:visited_countries).permit(:country)
	end

end

app/views/visited_countries/_visited_countries_partial.html.erb
<aside class="skills aside section">
<div class="section-inner">
    <h2 class="heading">Visited Countries 
    <% if (logged_in? && current_user == @user) %>
    <button onclick="javascript:showVisitedCountryEdit();">
    <i class="fa fa-cog" aria-hidden="true"></i>
    </button>
    <% end %>
    </h2>
    <div class="content">
        <!-- list of countries-->  
        <ul class="list-unstyled">
            <li class="item">
                <div>
                    <% if @visited_countries.any? %>
                        <%= render @visited_countries.order('country ASC') %>
                    <% else %>
                    Not set yet
                    <% end %>
                </div>
                <div id="visited_countries_edit" style="display: none;">
                    
                    <span class="title"><strong>Add a country</strong></span><br/>

                    <%= form_for VisitedCountry.new, url: visited_countries_add_country_path, method: :post, :remote => true do |f| %>
                        <%= f.country_select :country %>
                        <%= f.submit %>
                    <% end %>
                    
                </div>
            </li><!--//item-->
            
        </ul>           
    </div><!--//content-->  
</div><!--//section-inner-->                 
</aside><!--//section-->

app/views/visited_countries/_visited_country.html.erb
<span class="title">
	<strong>
		<%= ISO3166::Country[visited_country.country] %>
	</strong>
</span>
<!-- <a href="/visited_countries/remove_country"><i id="visited_country_remove_<%= visited_country.country%>" style="opacity: 0" class="fa fa-times" aria-hidden="true">
</i></a><br/>-->

<%= link_to visited_countries_remove_country_path(visited_country: visited_country.country), method: :post, :remote => true do %>
  <i id="visited_country_remove_<%= visited_country.country%>" style="display: none;" class="fa fa-times" aria-hidden="true">
</i>
<% end %><br/>

app/views/visited_countries/index.html.erb
<% if @countries.any? %>
<ul>
<% @countries.each do |country| %>
	<li><%= country %></li>
<% end %>
</ul>
<% end %>

app/views/visited_countries/refresh_visited_countries_partial.js.erb
setTimeout(function(){
 $('.visited_countries_div').html('<%= j(render partial: "/visited_countries/visited_countries_partial") %>')
}, 200)