config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources 'users'

  resources 'profiles'
  post "/profiles/update_profile" => "profiles#update_profile"
  post "/profiles/update_profile_about_me" => "profiles#update_profile_about_me"

  resources 'friendships'#, :except => [ :create ]
  post "/friendships/update_friendship" => "friendships#update_friendship"

  resources 'languages'
  get "/languages/learns_languages" => "languages#learns_languages"

  post "/languages_users/remove_user_language" => "languages_users#remove_user_language"
  post "/languages_users/add_user_language" => "languages_users#add_user_language"
  post "/languages_users/remove_user_learns_language" => "languages_users#remove_user_learns_language"
  post "/languages_users/add_user_learns_language" => "languages_users#add_user_learns_language"

  post "/users_learn_languages/remove_user_learns_language" => "users_learn_languages#remove_user_learns_language"
  post "/users_learn_languages/add_user_learns_language" => "users_learn_languages#add_user_learns_language"

  resources 'visited_countries'
  post "visited_countries/add_country" => "visited_countries#add_country"
  post "visited_countries/remove_country" => "visited_countries#remove_country"

  resources 'posts'
  post "posts/create_post" => "posts#create_post"

  resources 'messages', only: [:show, :create]
  #get "/messages/show_conversation" => "messages#show_conversation"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
end

app/models/languages_user.rb
class LanguagesUser < ApplicationRecord
	belongs_to :user
  	belongs_to :language
end

app/controllers/languages_users_controller.rb
class LanguagesUsersController < ApplicationController

	def remove_user_language
		#render plain: params[:remove_language_id].inspect
		@user_language = LanguagesUser.where(user_id: current_user.id, language_id: params[:remove_language_id]).delete_all
		@user = User.find(current_user.id)
		respond_to do |format|
    		format.js { render :action => "refresh_spoken_languages_div" }
 		end
	end

	def add_user_language
		#render plain: params[:languages_user][:language].inspect
		if LanguagesUser.where(user_id: current_user.id, language_id: params[:languages_user][:language], action: "speaks").exists?
			#LanguagesUser.where(user_id: current_user.id, language_id: params[:languages_user][:language],action: "speaks").delete_all
		elsif LanguagesUser.where(user_id: current_user.id, language_id: params[:languages_user][:language], action: "learns").exists?
			LanguagesUser.where(user_id: current_user.id, language_id: params[:languages_user][:language],action: "learns").delete_all
			LanguagesUser.create(user_id: current_user.id, language_id: params[:languages_user][:language], action: "speaks")
		else	
		LanguagesUser.create(user_id: current_user.id, language_id: params[:languages_user][:language], action: "speaks")
		end
		#redirect_to languages_path
		@user = User.find(current_user.id)
		respond_to do |format|
    		format.js { render :action => "refresh_spoken_languages_div" }
 		end
	end

	def remove_user_learns_language
		#render plain: params[:remove_language_id].inspect
		@user_language = LanguagesUser.where(user_id: current_user.id, language_id: params[:remove_language_id]).delete_all
		@user = User.find(current_user.id)
		respond_to do |format|
    		format.js { render :action => "refresh_spoken_languages_div" }
 		end
	end

	def add_user_learns_language
		#render plain: params[:languages_user][:language].inspect
		if LanguagesUser.where(user_id: current_user.id, language_id: params[:languages_user][:language], action: "learns").exists?
			#LanguagesUser.where(user_id: current_user.id, language_id: params[:languages_user][:language],action: "speaks").delete_all
		elsif LanguagesUser.where(user_id: current_user.id, language_id: params[:languages_user][:language], action: "speaks").exists?
			LanguagesUser.where(user_id: current_user.id, language_id: params[:languages_user][:language],action: "speaks").delete_all
			LanguagesUser.create(user_id: current_user.id, language_id: params[:languages_user][:language], action: "learns")
		else	
		LanguagesUser.create(user_id: current_user.id, language_id: params[:languages_user][:language], action: "learns")
		end
		#redirect_to languages_path
		@user = User.find(current_user.id)
		respond_to do |format|
    		format.js { render :action => "refresh_learning_languages_div" }
 		end
	end


end

app/views/languages_users/_learning_languages.html.erb
<h2 class="desc">Wants to learn 
<% if (logged_in? && current_user == @user) %>
    <% if (logged_in? && current_user == @user) %>
        <button onclick="javascript:showLearnLanguagesEdit();">
        <i class="fa fa-pencil" aria-hidden="true"></i>
        </button>
    <% end %>
<% end %>

</h2>   
<ul class="list-inline">
<% if @user.languages.any? %>
    <%  @user.languages.each do |lang| %>
        <% if user_learns_language?(lang.id) %>
            <li>
                <%= lang.language %>
                <%= link_to languages_users_remove_user_learns_language_path(:remove_language_id => lang.id ), method: :post, :remote => true do %>
                <i id="learn_language_remove_<%= lang.language%>" style="display: none;" class="fa fa-times" aria-hidden="true"></i>
                <% end %>
            </li>
        <% end %>    
    <% end %>
<% else %>
    <li>Not set yet</li> 
<% end %>   
<div id="learn_languages_edit" style="display: none;">
    <%= form_for LanguagesUser.new, url: languages_users_add_user_learns_language_path, method: :post, :remote => true do |f| %>
    <%= f.collection_select :language, Language.all, :id, :language %>
    <%= f.submit 'Add' %>
    <% end %>  
</div>      
</ul> 

app/views/languages_users/_spoken_languages.html.erb
<h2 class="desc">Speaks 
<% if (logged_in? && current_user == @user) %>
    <% if (logged_in? && current_user == @user) %>
        <button onclick="javascript:showSpeakLanguagesEdit();">
        <i class="fa fa-pencil" aria-hidden="true"></i>
        </button>
    <% end %>
<% end %>

</h2>   
<ul class="list-inline">
<% if @user.languages.any? %>
<%  @user.languages.each do |lang| %>
	<%if user_knows_language?(lang.id) %>
	    <li><%= lang.language %>
	    <%= link_to languages_users_remove_user_language_path(:remove_language_id => lang.id ), method: :post, :remote => true do %>
	    <i id="spoken_language_remove_<%= lang.language%>" class="fa fa-times" aria-hidden="true" style="display: none;"></i>
	    <% end %></li> 
	<% end %>
<% end %>
<% else %>
    <li>Not set yet</li> 
<% end %>  
<div id="spoken_languages_edit" style="display: none;">
    <%= form_for LanguagesUser.new, url: languages_users_add_user_language_path, method: :post, :remote => true do |f| %>
    <%= f.collection_select :language, Language.all, :id, :language %>
    <%= f.submit 'Add' %>
    <% end %>
</div>
</ul> 

app/views/languages_users/refresh_learning_languages_div.js.erb
setTimeout(function(){
 $('.learning_languages_div').html('<%= j(render partial: "/languages_users/learning_languages") %>')
 $('.spoken_languages_div').html('<%= j(render partial: "/languages_users/spoken_languages") %>')
 $('.languages_levels_div').html('<%= j(render partial: "/languages/languages_levels_partial") %>')
}, 200)

app/views/languages_users/refresh_spoken_languages_div.js.erb
setTimeout(function(){
 $('.spoken_languages_div').html('<%= j(render partial: "/languages_users/spoken_languages") %>')
 $('.learning_languages_div').html('<%= j(render partial: "/languages_users/learning_languages") %>')
 $('.languages_levels_div').html('<%= j(render partial: "/languages/languages_levels_partial") %>')
}, 200)